### ISSUE TITLE
Fvwm 2.6.5 Crashes on "Close" button click on Xaw based windows on OpenBSD 6.3

### ISSUE THREAD

**Issue by quirinpa** [fvwmorg/fvwm#63]
Greetings. You have created an admirable wm you guys; Which I use to make a user-friendly GUI for my mom and her OpenBSD 6.3 laptop, and I don't mind using, either.

I have the following binding in my .fvwm2rc:
```
Mouse 1 2 N Close
```

And when I click on button 2, Xaw-based apps (like bitmap), fvwm crashes and I'm greeted with the xenodm login screen. Curiously, this binding:
```
Key c A SM Close
```
Does not.

I can reproduce the problem with a .fvwm2rc with only the problematic binding on both my computer and my mom's.

I hope you can solve this, I'd love to help but I'm unfamiliar with the code base and am kind of a noob. Thanks.

**Comment by quirinpa** [comment]
Still crashes. How do I get a backtrace? Do you mean gdb?

**Comment by ThomasAdam** [comment]
Which application are you using which causes the crash?

**Comment by quirinpa** [comment]
Apparently it doesn't happen with xfontsel, which I suppose uses Xaw, I only know that it happens on "bitmap", my own code. I've just remembered, this also happens with wmaker dockapps.

**Comment by ThomasAdam** [comment]
Can you send me an example program then?

**Comment by quirinpa** [comment]
Sure. Please wait.

**Comment by quirinpa** [comment]
```c
#include <X11/Intrinsic.h>
#include <X11/Xaw/Command.h>

int main(int argc, char *argv[])
{
        Widget toplevel;
        Widget big_box;

        toplevel = XtInitialize(argv[0], "simple", NULL, 0, &argc, argv);
        XtCreateManagedWidget("test\n", commandWidgetClass, toplevel, NULL, 0);
        XtRealizeWidget(toplevel);
        XtMainLoop();
        return 0;
}
```

**Comment by ThomasAdam** [comment]
Thanks -- this works fine for me.  Check if there's a corefile, and use gdb to analyse it and send me a `bt`.

**Comment by quirinpa** [comment]
[fvwm.core](http://qnixsoft.com/fvwm.core)
[fvwm2.core](http://qnixsoft.com/fvwm2.core)

Sorry for the delay.

**Comment by ThomasAdam** [comment]
This doesn't help me.  You're going to have to build FVWM 2.6.7:

```
./configure && make CFLAGS="-ggdb -O0"
```

Make it crash, find the corefile and then use `gdb` to analyse it.

```
gdb /path/to/compiled/fvwm /path/to/corefile
(gdb) bt full
```

Then send me the output.

**Comment by quirinpa** [comment]
Sorry. Here it is:
```Currently logging to "gdb.txt".
Logs will be appended to the log file.
Output will be logged and displayed.
#0  0x00000966ba67c5a2 in __is_restack_needed (t=0x968d6e1f800, mode=SM_RAISE,
    do_restack_transients=0, is_new_window=0) at stack.c:882
No locals.
#1  0x00000966ba67c640 in __restack_window (t=0x968d6e1f800, mode=SM_RAISE,
    do_restack_transients=0, is_new_window=0, is_client_request=0)
    at stack.c:898
        s = (FvwmWindow *) 0x0
        r = (FvwmWindow *) 0x0
        tmp_r = {name = {name = 0x7f7ffffc83f0 " \204üÿ\177\177",
    name_list = 0x968e361acd6}, icon_name = {
    name = 0x10 <Address 0x10 out of bounds>, name_list = 0x20},
  visible_name = 0x969714a4000 "",
  visible_icon_name = 0x20 <Address 0x20 out of bounds>,
  style_name = 0x7f7ffffc8420 "0\205üÿ\177\177", name_count = 1422271238,
  icon_name_count = 2409, next = 0x320af220, prev = 0x968fe2d0ac0,
  stack_next = 0x23, stack_prev = 0x968e386fbe0, wins = {frame = 16,
    parent = 10349048933280, client = 140187732313120, title = 10346096077681,
    button_w = {32, 0, 10348476907520, 10348476911744, 140187732313392,
      10347998486834, 80, 10348476907552, 10348476911744, 32}, sides = {
      10348476911688, 0, 1, 72057594037927936}, corners = {0, 10342281248768,
      140187732313248, 1}, icon_title_w = 140187732313264,
    icon_pixmap_w = 549755813888, transientfor = 10348476907564}, flags = {
    common = {is_sticky_across_pages = 0, is_sticky_across_desks = 0,
      has_icon_font = 0, has_no_border = 0, has_window_font = 0,
      title_dir = 0, user_states = 0, s = {do_circulate_skip = 0,
        do_circulate_skip_icon = 0, do_circulate_skip_shaded = 0,
        do_ewmh_donate_icon = 1, do_ewmh_donate_mini_icon = 1,
        do_ewmh_ignore_state_hints = 1, do_ewmh_ignore_strut_hints = 1,
        do_ewmh_mini_icon_override = 1, do_ewmh_use_stacking_hints = 0,
        do_ewmh_ignore_window_type = 0, do_iconify_window_groups = 1,
        do_ignore_icon_boxes = 0, do_ignore_restack = 0,
        do_use_window_group_hint = 0, do_lower_transient = 0,
        do_not_show_on_map = 1, do_raise_transient = 0, do_resize_opaque = 0,
        do_shrink_windowshade = 1, do_stack_transient_parent = 1,
        do_window_list_skip = 1, ewmh_maximize_mode = 3,
        has_depressable_border = 1, has_mwm_border = 1, has_mwm_buttons = 1,
        has_mwm_override = 1, has_no_icon_title = 1, has_override_size = 1,
        has_stippled_title = 1, has_stippled_icon_title = 1,
        has_no_sticky_stippled_title = 1,
        has_no_sticky_stippled_icon_title = 1, icon_override = 3,
        is_bottom_title_rotated = 1, is_fixed = 1, is_fixed_ppos = 1,
        is_uniconifiable = 1, is_unmaximizable = 0, is_unclosable = 1,
        is_maximize_fixed_size_disallowed = 1,
        is_icon_sticky_across_pages = 1, is_icon_sticky_across_desks = 1,
        is_icon_suppressed = 1, is_left_title_rotated_cw = 1, is_lenient = 1,
        is_size_fixed = 0, is_psize_fixed = 0, is_right_title_rotated_cw = 0,
        is_top_title_rotated = 0, use_icon_position_hint = 0,
        use_indexed_window_name = 0, use_indexed_icon_name = 0,
        windowshade_laziness = 0, use_title_decor_rotation = 0,
        focus_policy = {do_raise_focused_click = {client = 0, decor = 0,
            icon = 1}, do_raise_unfocused_click = {client = 0, decor = 0,
            icon = 0}, do_focus_click = {client = 1, decor = 1, icon = 1},
          do_focus_enter = 1, do_unfocus_leave = 0, do_focus_by_program = 1,
          do_focus_by_function = 0, do_warp_pointer_on_focus_func = 0,
          is_lenient = 1, use_mouse_buttons = 21, use_modifiers = 135,
          do_pass_focus_click = 1, do_pass_raise_click = 1,
          do_ignore_focus_click_motion = 1, do_ignore_raise_click_motion = 1,
          do_allow_func_focus_click = 1, do_allow_func_raise_click = 1,
          do_open_grabs_focus = 0, do_open_grabs_focus_transient = 0,
          do_override_grab_focus = 0, do_close_releases_focus = 0,
          do_close_releases_focus_transient = 0,
          do_override_release_focus = 0, do_sort_windowlist_by = 0}}},
    cr_motion_method = 0, was_cr_motion_method_detected = 0,
    does_wm_delete_window = 0, does_wm_take_focus = 0, do_force_next_cr = 0,
    do_force_next_pn = 0, do_iconify_after_map = 0,
    do_disable_constrain_size_fullscreen = 0, do_reuse_destroyed = 0,
    has_handles = 0, has_icon_changed = 0, has_title = 0,
    has_new_wm_normal_hints = 0, is_decor_changed = 0, is_iconify_pending = 0,
    is_focused_on_other_desk = 0, is_focus_change_broadcast_pending = 0,
    is_fully_visible = 0, is_iconified = 0, is_iconified_by_parent = 0,
    is_icon_entered = 0, is_icon_font_loaded = 0, is_icon_moved = 0,
    is_icon_ours = 0, is_icon_shaped = 0, is_icon_unmapped = 0,
    is_in_transient_subtree = 0, is_mapped = 0, is_map_pending = 0,
    is_maximized = 0, is_name_changed = 0, is_partially_visible = 0,
    is_pixmap_ours = 0, is_placed_by_fvwm = 0, is_scheduled_for_destroy = 0,
    is_scheduled_for_raise = 1, is_size_inc_set = 1, is_style_deleted = 0,
    is_tear_off_menu = 0, is_transient = 1, is_window_drawn_once = 0,
    is_viewport_moved = 1, is_window_being_moved_opaque = 0,
    is_window_font_loaded = 0, is_window_shaded = 0,
    used_title_dir_for_shading = 0, shaded_dir = 1,
    using_default_icon_font = 1, using_default_window_font = 1,
    was_icon_hint_provided = 3, was_icon_name_provided = 1,
    was_never_drawn = 1, has_ewmh_wm_name = 1, has_ewmh_wm_icon_name = 1,
    has_ewmh_wm_icon_hint = 3, has_ewmh_mini_icon = 1, has_ewmh_wm_pid = 1,
    use_ewmh_icon = 1, is_ewmh_modal = 1, is_ewmh_fullscreen = 1,
    has_ewmh_init_fullscreen_state = 3, has_ewmh_init_hidden_state = 3,
    has_ewmh_init_maxhoriz_state = 3, has_ewmh_init_maxvert_state = 2,
    has_ewmh_init_modal_state = 3, has_ewmh_init_shaded_state = 3,
    has_ewmh_init_skip_pager_state = 3, has_ewmh_init_skip_taskbar_state = 0,
    has_ewmh_init_sticky_state = 0, has_ewmh_init_wm_desktop = 0},
  decor_state = {buttons_drawn = 638, buttons_lit = 790,
    buttons_inverted = 565, buttons_toggled = 360, parts_drawn = 2,
    parts_lit = 2560, parts_inverted = 2147}, nr_left_buttons = 2408,
  nr_right_buttons = 0, decor = 0x1fc38565bf8174ef, wShaped = -1082034961,
  title_background_pixmap = 1014731240496053762, boundary_width = 1,
  unshaped_boundary_width = 0, corner_width = 0, visual_corner_width = 0,
  title_font = 0x7f7ffffc8558, title_text_offset = 0, title_length = 0,
  title_thickness = 0, title_text_rotation = 1900691456, icon_g = {
    picture_w_g = {x = 2409, y = -480550508, width = 2408, height = 80},
    title_w_g = {x = 0, y = 1900691456, width = 2409, height = -227760},
    title_text_width = 32639}, icon_border_width = 8719, iconDepth = 2409,
  iconPixmap = 32, icon_maskPixmap = 10349048938052,
  icon_alphaPixmap = 10346098473472, icon_nalloc_pixels = 839578144,
  icon_alloc_pixels = 0x968e3863a00, icon_no_limit = 0, icon_font = 0x23,
  attr_backup = {backing_store = -477692960, border_width = 2408, depth = 0,
    bit_gravity = 0, is_bit_gravity_stored = 0, visual = 0x7f7ffffc85c0,
    colormap = 1}, hints = {flags = 140187732313552, x = 80, y = 0,
    width = 1900691500, height = 2409, min_width = 4096, min_height = 0,
    max_width = -227776, max_height = 32639, width_inc = -480134236,
    height_inc = 2408, min_aspect = {x = -1082034961, y = 532907365},
    max_aspect = {x = 0, y = 0}, base_width = -227760, base_height = 32639,
    win_gravity = -480486786}, orig_hints = {width_inc = -477742592,
    height_inc = 2408}, wmhints = 0x4cc27680, class = {
    res_name = 0x7f7ffffc8680 "°\206üÿ\177\177",
    res_class = 0x968e361bba4 "I\213\206\220\022"}, Desk = -227760,
  FocusDesk = 32639, DeIconifyDesk = -480486010, mini_pixmap_file = 0x0,
  mini_icon = 0x0,
  icon_bitmap_file = 0x714a4018 <Address 0x714a4018 out of bounds>, g = {
    frame = {x = -30602560, y = 2408, width = -1822250080, height = 2409},
    normal = {x = 1, y = 0, width = 35, height = 0}, max = {x = -477692960,
      y = 2408, width = -30602560, height = 2408}, max_defect = {
      width = -1822250080, height = 2409}, max_offset = {x = -227664,
      y = 32639}}, mwm_hints = 0x968e361b43a, ol_hints = 0, functions = 0,
  cmap_windows = 0x968fe2d0ac0, number_cmap_windows = 183300096, colors = {
    fore = 10346545611520, back = 140187732313888, hilight = 10345796109769,
    shadow = 10349048933280}, hicolors = {fore = 0, back = 140187732313920,
    hilight = 4294967296, shadow = 0}, border_colors = {fore = 10346973702880,
    back = 18442041070934977862, hilight = 10336821429608,
    shadow = 10336821408640}, border_hicolors = {fore = 10336821448568,
    back = 10346759516160, hilight = 1232, shadow = 140187732314000},
  cs = -780149959, cs_hi = 2408, border_cs = -689833328, border_cs_hi = 2408,
  icon_title_cs = -1164872828, icon_title_cs_hi = 2406,
  icon_background_cs = 204472577, buttons = 1232, IconBoxes = 0xe0025000e0025,
  default_layer = 0, layer = 0, min_icon_width = 70 'F',
  max_icon_width = 109 'm', min_icon_height = 62 '>',
  max_icon_height = 214 'Ö', icon_resize_type = 19108,
  icon_background_padding = 239 'ï', icon_background_relief = -1 'ÿ',
  icon_title_relief = 64 '@', min_window_width = 2409,
  min_window_height = -689833328, max_window_width = 2408,
  max_window_height = 128, shade_anim_steps = 0, grabbed_buttons = 104 'h',
  snap_attraction = {proximity = 32639, mode = 1, types = SNAP_NONE},
  snap_grid_x = -227328, snap_grid_y = 32639,
  edge_delay_ms_move = -1167245502, edge_delay_ms_resize = 2406,
  edge_resistance_move = -1164872832, edge_resistance_xinerama_move = 2406,
  focus_model = 132 '\204', pl_penalty = {normal = 3.37152411e-42,
    ontop = -nan(0x7c8914), icon = 4.57369806e-41, sticky = 0, below = 0,
    strut = -0.00110970484}, pl_percent_penalty = {p99 = 2406,
    p95 = -1164872832, p85 = 2406, p75 = -1164832904},
  placed_by_button = 102 'f', ewmh_window_type = -1164851864,
  ewmh_icon_geometry = {x = 2406, y = 1232, width = 0, height = 183300096},
  strut = {left = 2409, right = 0, top = 1, bottom = 0}, dyn_strut = {
    left = 0, right = -227040, top = 32639, bottom = -1167881500},
  ewmh_icon_height = 2406, ewmh_icon_width = -1164872832,
  ewmh_mini_icon_height = 2406, ewmh_mini_icon_width = -1164872828,
  ewmh_hint_layer = 2406, ewmh_normal_layer = -227052,
  ewmh_hint_desktop = 128, fullscreen = {g = {frame = {x = 0, y = 0,
        width = 0, height = 1}, normal = {x = -134054475, y = 2408,
        width = -706274048, height = 2408}, max = {x = 397486821, y = 2409,
        width = -134055136, height = 2408}, max_defect = {width = 40,
        height = 48}, max_offset = {x = -226992, y = 32639}},
    is_iconified = -227184, is_shaded = 32639, was_maximized = 0}, scratch = {
    p = 0x0, i = -689833984}}
        count = -538976289
#2  0x00000966ba67ca92 in __raise_or_lower_window (t=0x968d6e1f800,
    mode=SM_RAISE, allow_recursion=1, is_new_window=0, is_client_request=0)
    at stack.c:1084
        t2 = (FvwmWindow *) 0x966ba689b37
        do_move_transients = 0
#3  0x00000966ba67cb94 in raise_or_lower_window (t=0x968d6e1f800,
    mode=SM_RAISE, allow_recursion=1, is_new_window=0, is_client_request=0)
    at stack.c:1159
        fw = (FvwmWindow *) 0x0
#4  0x00000966ba67d86f in RaiseWindow (t=0x968d6e1f800, is_client_request=0)
    at stack.c:1716
No locals.
#5  0x00000966ba633676 in __handle_bpress_on_managed (exc=0x968d5e71000)
    at events.c:1809
        action = 0x96908b33420 "Close"
        f = {do_forbid_function = 0, do_focus = 1, do_swallow_click = 1,
  do_raise = 0}
        fw = (FvwmWindow * const) 0x968d6e1f800
        e = (XEvent *) 0x968d5e71038
#6  0x00000966ba6337fb in HandleButtonPress (ea=0x7f7ffffc8a88)
    at events.c:1854
No locals.
#7  0x00000966ba637d10 in dispatch_event (e=0x7f7ffffc8ad0) at events.c:4306
        ea = {exc = 0x968d5e71000}
        ecc = {type = EXCT_EVENT, x = {etrigger = 0x7f7ffffc8ad0,
    elast = 0x0}, w = {fw = 0x968d6e1f800, w = 10486112, wcontext = 128}, m = {
    module = 0x0}}
        dummyw = 10486112
        w = 10486112
        fw = (FvwmWindow *) 0x968d6e1f800
        event_group = (event_group_t *) 0x968bcc404e0
#8  0x00000966ba637e11 in HandleEvents () at events.c:4357
        ev = {type = 4, xany = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, window = 10486112}, xkey = {type = 4,
    serial = 3070, send_event = 0, display = 0x9690aecf000, window = 10486112,
    root = 1232, subwindow = 0, time = 390383705, x = 2, y = 9, x_root = 37,
    y_root = 14, state = 0, keycode = 1, same_screen = 1}, xbutton = {
    type = 4, serial = 3070, send_event = 0, display = 0x9690aecf000,
    window = 10486112, root = 1232, subwindow = 0, time = 390383705, x = 2,
    y = 9, x_root = 37, y_root = 14, state = 0, button = 1, same_screen = 1},
  xmotion = {type = 4, serial = 3070, send_event = 0, display = 0x9690aecf000,
    window = 10486112, root = 1232, subwindow = 0, time = 390383705, x = 2,
    y = 9, x_root = 37, y_root = 14, state = 0, is_hint = 1 '\001',
    same_screen = 1}, xcrossing = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, window = 10486112, root = 1232, subwindow = 0,
    time = 390383705, x = 2, y = 9, x_root = 37, y_root = 14, mode = 0,
    detail = 1, same_screen = 1, focus = 0, state = 0}, xfocus = {type = 4,
    serial = 3070, send_event = 0, display = 0x9690aecf000, window = 10486112,
    mode = 1232, detail = 0}, xexpose = {type = 4, serial = 3070,
    send_event = 0, display = 0x9690aecf000, window = 10486112, x = 1232,
    y = 0, width = 0, height = 0, count = 390383705}, xgraphicsexpose = {
    type = 4, serial = 3070, send_event = 0, display = 0x9690aecf000,
    drawable = 10486112, x = 1232, y = 0, width = 0, height = 0,
    count = 390383705, major_code = 0, minor_code = 2}, xnoexpose = {type = 4,
    serial = 3070, send_event = 0, display = 0x9690aecf000,
    drawable = 10486112, major_code = 1232, minor_code = 0}, xvisibility = {
    type = 4, serial = 3070, send_event = 0, display = 0x9690aecf000,
    window = 10486112, state = 1232}, xcreatewindow = {type = 4,
    serial = 3070, send_event = 0, display = 0x9690aecf000, parent = 10486112,
    window = 1232, x = 0, y = 0, width = 390383705, height = 0,
    border_width = 2, override_redirect = 9}, xdestroywindow = {type = 4,
    serial = 3070, send_event = 0, display = 0x9690aecf000, event = 10486112,
    window = 1232}, xunmap = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, event = 10486112, window = 1232,
    from_configure = 0}, xmap = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, event = 10486112, window = 1232,
    override_redirect = 0}, xmaprequest = {type = 4, serial = 3070,
    send_event = 0, display = 0x9690aecf000, parent = 10486112,
    window = 1232}, xreparent = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, event = 10486112, window = 1232, parent = 0,
    x = 390383705, y = 0, override_redirect = 2}, xconfigure = {type = 4,
    serial = 3070, send_event = 0, display = 0x9690aecf000, event = 10486112,
    window = 1232, x = 0, y = 0, width = 390383705, height = 0,
    border_width = 2, above = 60129542181, override_redirect = 0}, xgravity = {
    type = 4, serial = 3070, send_event = 0, display = 0x9690aecf000,
    event = 10486112, window = 1232, x = 0, y = 0}, xresizerequest = {
    type = 4, serial = 3070, send_event = 0, display = 0x9690aecf000,
    window = 10486112, width = 1232, height = 0}, xconfigurerequest = {
    type = 4, serial = 3070, send_event = 0, display = 0x9690aecf000,
    parent = 10486112, window = 1232, x = 0, y = 0, width = 390383705,
    height = 0, border_width = 2, above = 60129542181, detail = 0,
    value_mask = 1}, xcirculate = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, event = 10486112, window = 1232, place = 0},
  xcirculaterequest = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, parent = 10486112, window = 1232, place = 0},
  xproperty = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, window = 10486112, atom = 1232, time = 0,
    state = 390383705}, xselectionclear = {type = 4, serial = 3070,
    send_event = 0, display = 0x9690aecf000, window = 10486112,
    selection = 1232, time = 0}, xselectionrequest = {type = 4, serial = 3070,
    event = 10486112, window = 1232, x = 0, y = 0}, xresizerequest = {
    type = 4, serial = 3070, send_event = 0, display = 0x9690aecf000,
    window = 10486112, width = 1232, height = 0}, xconfigurerequest = {
    type = 4, serial = 3070, send_event = 0, display = 0x9690aecf000,
    parent = 10486112, window = 1232, x = 0, y = 0, width = 390383705,
    height = 0, border_width = 2, above = 60129542181, detail = 0,
    value_mask = 1}, xcirculate = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, event = 10486112, window = 1232, place = 0},
  xcirculaterequest = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, parent = 10486112, window = 1232, place = 0},
  xproperty = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, window = 10486112, atom = 1232, time = 0,
    state = 390383705}, xselectionclear = {type = 4, serial = 3070,
    send_event = 0, display = 0x9690aecf000, window = 10486112,
    selection = 1232, time = 0}, xselectionrequest = {type = 4, serial = 3070,
    send_event = 0, display = 0x9690aecf000, owner = 10486112,
    requestor = 1232, selection = 0, target = 390383705,
    property = 38654705666, time = 60129542181}, xselection = {type = 4,
    serial = 3070, send_event = 0, display = 0x9690aecf000,
    requestor = 10486112, selection = 1232, target = 0, property = 390383705,
    time = 38654705666}, xcolormap = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, window = 10486112, colormap = 1232, new = 0,
    state = 0}, xclient = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, window = 10486112, message_type = 1232,
    format = 0, data = {
      b = "YÈD\027\000\000\000\000\002\000\000\000\t\000\000\000%\000\000",
      s = {-14247, 5956, 0, 0, 2, 0, 9, 0, 37, 0}, l = {390383705,
        38654705666, 60129542181, 4294967296, 1}}}, xmapping = {type = 4,
    serial = 3070, send_event = 0, display = 0x9690aecf000, window = 10486112,
    request = 1232, first_keycode = 0, count = 0}, xerror = {type = 4,
    display = 0xbfe, resourceid = 16131858539135107072,
    serial = 10346759516160, error_code = 96 '`', request_code = 1 '\001',
    minor_code = 160 ' '}, xkeymap = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, window = 10486112,
    key_vector = "Ð\004", '\0' <repeats 14 times>, "YÈD\027\000\000\000\000\002\000\000\000\t\000\000"}, xgeneric = {type = 4, serial = 3070, send_event = 0,
    display = 0x9690aecf000, extension = 10486112, evtype = 0}, xcookie = {
    type = 4, serial = 3070, send_event = 0, display = 0x9690aecf000,
    extension = 10486112, evtype = 0, cookie = 1232, data = 0x0}, pad = {
    -2314885534574444540, 3070, -2314885534574444544, 10346759516160,
    10486112, 1232, 0, 390383705, 38654705666, 60129542181, 4294967296, 1,
    -2314885534574444544, -2314885530818453537 <repeats 11 times>}}
#9  0x00000966ba661763 in main (argc=2, argv=0x7f7ffffc8f68) at fvwm.c:2599
        valuemask = 8202
        attributes = {background_pixmap = 0, background_pixel = 12500670,
  border_pixmap = 10347437039024, border_pixel = 0, bit_gravity = 0,
  win_gravity = 0, backing_store = 0, backing_planes = 140187732315312,
  backing_pixel = 10346095973029, save_under = -477742592,
  event_mask = 2097155, do_not_propagate_mask = 10347437052864,
  override_redirect = 1, colormap = 32, cursor = 10485773}
        i = 1
        len = 2
        display_string = 0x969580bcef0 'ß' <repeats 32 times>
        do_force_single_screen = 0
        single_screen_num = -1
        replace_wm = 0
        visualClass = -1
        visualId = -1
        colorLimitop = {color_limit = -1, strict = -1, allocate = -1,
  not_dynamic = -1, use_named_table = -1}
        exc = (const exec_context_t *) 0x969636cf200
        ecc = {type = EXCT_INIT, x = {etrigger = 0x9699ce0dc96, elast = 0x85},
  w = {fw = 0x969a01724a0, w = 10346018705408, wcontext = 8}, m = {
    module = 0x7f7ffffc8d40}}

```

**Comment by quirinpa** [comment]
Were you able to reach any conclusion regarding this issue, or have I done something wrong? I don't mean to be a pain in the ass, especially because I haven't taken the time to look at the code (assuming I could understand it, with time). And I don't mean to politicize this, but I disagree that this issue is "closed". You are free to use this platform however you choose, but I really wished for this to be solved. Already you have put a lot of time and effort into fvwm, and you gave it away for free. That is amazing and I respect it a lot. And I don't mean to be rude. Have a nice day.
